# Generated by Django 3.1.3 on 2020-12-04 17:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_auto_20201204_1840'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reply',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='store.product'),
        ),
    ]
