# Generated by Django 3.1.4 on 2020-12-09 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aquarium', '0003_auto_20201204_2038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='availability',
            field=models.BooleanField(),
        ),
    ]
