# Generated by Django 3.1.4 on 2020-12-09 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aquarium', '0004_auto_20201209_1238'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='availability',
            field=models.CharField(choices=[['Available', 'Available'], ['Sold Out', 'Sold Out']], max_length=20),
        ),
    ]
