# Generated by Django 3.1.3 on 2020-12-04 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Feedbacks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=150)),
                ('subject', models.CharField(max_length=100)),
                ('message', models.TextField(max_length=5000)),
            ],
        ),
        migrations.CreateModel(
            name='Subscriber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Testimonials',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(max_length=5000)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Upload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('availability', models.CharField(choices=[['Available', 'Available'], ['Rented', 'Rented'], ['Sold', 'Sold']], max_length=30)),
                ('category', models.CharField(choices=[['For Rent', 'For Rent'], ['For Sale', 'For Sale'], ['Joint Venture', 'Joint Venture'], ['Short Let', 'Short Let']], max_length=30)),
                ('type', models.CharField(choices=[['Flat', 'Flat'], ['House', 'House'], ['Land', 'Land'], ['Commercial Property', 'Commercial Property']], max_length=30)),
                ('subtype', models.CharField(choices=[['Mini Flat', 'Mini Flat'], ['Self Contained(Single Rooms)', 'Self Contained(Single Rooms)'], ['Detached Bungalow', 'Mini Flat'], ['Detached Duplex', 'Detached Duplex'], ['Semi-detached Bungalow', 'Semi-detached Bungalow'], ['Semi-detached Duplex', 'Semi-detached Duplex'], ['Terraced Bungalow', 'Terraced Bungalow'], ['Terraced Duplex', 'Terraced Duplex']], max_length=30)),
                ('locality', models.CharField(blank=True, max_length=30)),
                ('street', models.CharField(max_length=30)),
                ('description', models.TextField(max_length=5000)),
                ('price', models.CharField(max_length=100)),
                ('bedrooms', models.CharField(blank=True, choices=[('3', '3'), ('1', '1'), ('4', '4'), ('7', '7'), ('8', '8'), ('0', '0'), ('2', '2'), ('9', '9'), ('5', '5'), ('6', '6')], max_length=300)),
                ('toilets', models.CharField(blank=True, choices=[('3', '3'), ('1', '1'), ('4', '4'), ('7', '7'), ('8', '8'), ('0', '0'), ('2', '2'), ('9', '9'), ('5', '5'), ('6', '6')], max_length=30)),
                ('bathrooms', models.CharField(blank=True, choices=[('3', '3'), ('1', '1'), ('4', '4'), ('7', '7'), ('8', '8'), ('0', '0'), ('2', '2'), ('9', '9'), ('5', '5'), ('6', '6')], max_length=30)),
                ('parking', models.CharField(blank=True, choices=[('3', '3'), ('1', '1'), ('4', '4'), ('7', '7'), ('8', '8'), ('0', '0'), ('2', '2'), ('9', '9'), ('5', '5'), ('6', '6')], max_length=30)),
                ('toiletArea', models.CharField(blank=True, max_length=300)),
                ('coveredArea', models.CharField(blank=True, max_length=300)),
                ('videoLink', models.CharField(max_length=3000)),
                ('image1', models.FileField(null=True, upload_to='media/')),
                ('image2', models.FileField(null=True, upload_to='media/')),
                ('image3', models.FileField(null=True, upload_to='media/')),
                ('image4', models.FileField(blank=True, null=True, upload_to='media/')),
            ],
        ),
    ]
