# Generated by Django 3.1.3 on 2020-12-04 15:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('homes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upload',
            name='bathrooms',
            field=models.CharField(blank=True, choices=[('1', '1'), ('4', '4'), ('3', '3'), ('2', '2'), ('5', '5'), ('7', '7'), ('6', '6'), ('8', '8'), ('9', '9'), ('0', '0')], max_length=30),
        ),
        migrations.AlterField(
            model_name='upload',
            name='bedrooms',
            field=models.CharField(blank=True, choices=[('1', '1'), ('4', '4'), ('3', '3'), ('2', '2'), ('5', '5'), ('7', '7'), ('6', '6'), ('8', '8'), ('9', '9'), ('0', '0')], max_length=300),
        ),
        migrations.AlterField(
            model_name='upload',
            name='parking',
            field=models.CharField(blank=True, choices=[('1', '1'), ('4', '4'), ('3', '3'), ('2', '2'), ('5', '5'), ('7', '7'), ('6', '6'), ('8', '8'), ('9', '9'), ('0', '0')], max_length=30),
        ),
        migrations.AlterField(
            model_name='upload',
            name='toilets',
            field=models.CharField(blank=True, choices=[('1', '1'), ('4', '4'), ('3', '3'), ('2', '2'), ('5', '5'), ('7', '7'), ('6', '6'), ('8', '8'), ('9', '9'), ('0', '0')], max_length=30),
        ),
        migrations.CreateModel(
            name='Reply',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500, null=True)),
                ('email', models.EmailField(max_length=500, null=True)),
                ('comment', models.TextField(max_length=100000, null=True)),
                ('date', models.DateField(auto_now_add=True, null=True)),
                ('Upload', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='homes.upload')),
            ],
        ),
    ]
