# Generated by Django 3.1.3 on 2020-12-04 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homes', '0002_auto_20201204_1637'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upload',
            name='bathrooms',
            field=models.CharField(blank=True, choices=[('7', '7'), ('1', '1'), ('6', '6'), ('2', '2'), ('8', '8'), ('5', '5'), ('3', '3'), ('4', '4'), ('0', '0'), ('9', '9')], max_length=30),
        ),
        migrations.AlterField(
            model_name='upload',
            name='bedrooms',
            field=models.CharField(blank=True, choices=[('7', '7'), ('1', '1'), ('6', '6'), ('2', '2'), ('8', '8'), ('5', '5'), ('3', '3'), ('4', '4'), ('0', '0'), ('9', '9')], max_length=300),
        ),
        migrations.AlterField(
            model_name='upload',
            name='parking',
            field=models.CharField(blank=True, choices=[('7', '7'), ('1', '1'), ('6', '6'), ('2', '2'), ('8', '8'), ('5', '5'), ('3', '3'), ('4', '4'), ('0', '0'), ('9', '9')], max_length=30),
        ),
        migrations.AlterField(
            model_name='upload',
            name='toilets',
            field=models.CharField(blank=True, choices=[('7', '7'), ('1', '1'), ('6', '6'), ('2', '2'), ('8', '8'), ('5', '5'), ('3', '3'), ('4', '4'), ('0', '0'), ('9', '9')], max_length=30),
        ),
    ]
