# Generated by Django 3.1.3 on 2020-12-04 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homes', '0003_auto_20201204_1839'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upload',
            name='bathrooms',
            field=models.CharField(blank=True, choices=[('6', '6'), ('1', '1'), ('9', '9'), ('4', '4'), ('7', '7'), ('0', '0'), ('3', '3'), ('5', '5'), ('8', '8'), ('2', '2')], max_length=30),
        ),
        migrations.AlterField(
            model_name='upload',
            name='bedrooms',
            field=models.CharField(blank=True, choices=[('6', '6'), ('1', '1'), ('9', '9'), ('4', '4'), ('7', '7'), ('0', '0'), ('3', '3'), ('5', '5'), ('8', '8'), ('2', '2')], max_length=300),
        ),
        migrations.AlterField(
            model_name='upload',
            name='parking',
            field=models.CharField(blank=True, choices=[('6', '6'), ('1', '1'), ('9', '9'), ('4', '4'), ('7', '7'), ('0', '0'), ('3', '3'), ('5', '5'), ('8', '8'), ('2', '2')], max_length=30),
        ),
        migrations.AlterField(
            model_name='upload',
            name='toilets',
            field=models.CharField(blank=True, choices=[('6', '6'), ('1', '1'), ('9', '9'), ('4', '4'), ('7', '7'), ('0', '0'), ('3', '3'), ('5', '5'), ('8', '8'), ('2', '2')], max_length=30),
        ),
    ]
