# Generated by Django 3.1.3 on 2020-12-05 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homes', '0007_auto_20201204_2038'),
    ]

    operations = [
        migrations.AddField(
            model_name='upload',
            name='image5',
            field=models.FileField(blank=True, null=True, upload_to='media/'),
        ),
        migrations.AddField(
            model_name='upload',
            name='image6',
            field=models.FileField(blank=True, null=True, upload_to='media/'),
        ),
        migrations.AlterField(
            model_name='upload',
            name='bathrooms',
            field=models.CharField(blank=True, choices=[('4', '4'), ('2', '2'), ('0', '0'), ('5', '5'), ('9', '9'), ('6', '6'), ('7', '7'), ('3', '3'), ('1', '1'), ('8', '8')], max_length=30),
        ),
        migrations.AlterField(
            model_name='upload',
            name='bedrooms',
            field=models.CharField(blank=True, choices=[('4', '4'), ('2', '2'), ('0', '0'), ('5', '5'), ('9', '9'), ('6', '6'), ('7', '7'), ('3', '3'), ('1', '1'), ('8', '8')], max_length=300),
        ),
        migrations.AlterField(
            model_name='upload',
            name='parking',
            field=models.CharField(blank=True, choices=[('4', '4'), ('2', '2'), ('0', '0'), ('5', '5'), ('9', '9'), ('6', '6'), ('7', '7'), ('3', '3'), ('1', '1'), ('8', '8')], max_length=30),
        ),
        migrations.AlterField(
            model_name='upload',
            name='toilets',
            field=models.CharField(blank=True, choices=[('4', '4'), ('2', '2'), ('0', '0'), ('5', '5'), ('9', '9'), ('6', '6'), ('7', '7'), ('3', '3'), ('1', '1'), ('8', '8')], max_length=30),
        ),
    ]
