# Generated by Django 3.1.3 on 2020-12-05 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homes', '0009_auto_20201205_1507'),
    ]

    operations = [
        migrations.AddField(
            model_name='upload',
            name='numberOfImages',
            field=models.CharField(choices=[('4', '4'), ('3', '3'), ('1', '1'), ('5', '5'), ('6', '6'), ('0', '0'), ('2', '2')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='upload',
            name='bathrooms',
            field=models.CharField(blank=True, choices=[('9', '9'), ('4', '4'), ('3', '3'), ('1', '1'), ('5', '5'), ('6', '6'), ('7', '7'), ('0', '0'), ('8', '8'), ('2', '2')], max_length=30),
        ),
        migrations.AlterField(
            model_name='upload',
            name='bedrooms',
            field=models.CharField(blank=True, choices=[('9', '9'), ('4', '4'), ('3', '3'), ('1', '1'), ('5', '5'), ('6', '6'), ('7', '7'), ('0', '0'), ('8', '8'), ('2', '2')], max_length=300),
        ),
        migrations.AlterField(
            model_name='upload',
            name='parking',
            field=models.CharField(blank=True, choices=[('9', '9'), ('4', '4'), ('3', '3'), ('1', '1'), ('5', '5'), ('6', '6'), ('7', '7'), ('0', '0'), ('8', '8'), ('2', '2')], max_length=30),
        ),
        migrations.AlterField(
            model_name='upload',
            name='toilets',
            field=models.CharField(blank=True, choices=[('9', '9'), ('4', '4'), ('3', '3'), ('1', '1'), ('5', '5'), ('6', '6'), ('7', '7'), ('0', '0'), ('8', '8'), ('2', '2')], max_length=30),
        ),
    ]
