# Generated by Django 3.1.3 on 2020-12-05 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homes', '0011_auto_20201205_1600'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upload',
            name='bathrooms',
            field=models.CharField(blank=True, choices=[('2', '2'), ('0', '0'), ('4', '4'), ('7', '7'), ('8', '8'), ('9', '9'), ('5', '5'), ('6', '6'), ('3', '3'), ('1', '1')], max_length=30),
        ),
        migrations.AlterField(
            model_name='upload',
            name='bedrooms',
            field=models.CharField(blank=True, choices=[('2', '2'), ('0', '0'), ('4', '4'), ('7', '7'), ('8', '8'), ('9', '9'), ('5', '5'), ('6', '6'), ('3', '3'), ('1', '1')], max_length=300),
        ),
        migrations.AlterField(
            model_name='upload',
            name='numberOfImages',
            field=models.CharField(choices=[('2', '2'), ('0', '0'), ('4', '4'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10'), ('5', '5'), ('6', '6'), ('3', '3'), ('1', '1')], max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='upload',
            name='parking',
            field=models.CharField(blank=True, choices=[('2', '2'), ('0', '0'), ('4', '4'), ('7', '7'), ('8', '8'), ('9', '9'), ('5', '5'), ('6', '6'), ('3', '3'), ('1', '1')], max_length=30),
        ),
        migrations.AlterField(
            model_name='upload',
            name='toilets',
            field=models.CharField(blank=True, choices=[('2', '2'), ('0', '0'), ('4', '4'), ('7', '7'), ('8', '8'), ('9', '9'), ('5', '5'), ('6', '6'), ('3', '3'), ('1', '1')], max_length=30),
        ),
    ]
