# Generated by Django 3.1.3 on 2020-12-05 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homes', '0012_auto_20201205_1601'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upload',
            name='bathrooms',
            field=models.CharField(blank=True, choices=[('4', '4'), ('6', '6'), ('3', '3'), ('2', '2'), ('7', '7'), ('9', '9'), ('0', '0'), ('8', '8'), ('5', '5'), ('1', '1')], max_length=30),
        ),
        migrations.AlterField(
            model_name='upload',
            name='bedrooms',
            field=models.CharField(blank=True, choices=[('4', '4'), ('6', '6'), ('3', '3'), ('2', '2'), ('7', '7'), ('9', '9'), ('0', '0'), ('8', '8'), ('5', '5'), ('1', '1')], max_length=300),
        ),
        migrations.AlterField(
            model_name='upload',
            name='numberOfImages',
            field=models.CharField(choices=[('4', '4'), ('6', '6'), ('3', '3'), ('2', '2'), ('7', '7'), ('9', '9'), ('0', '0'), ('8', '8'), ('5', '5'), ('10', '10'), ('1', '1')], max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='upload',
            name='parking',
            field=models.CharField(blank=True, choices=[('4', '4'), ('6', '6'), ('3', '3'), ('2', '2'), ('7', '7'), ('9', '9'), ('0', '0'), ('8', '8'), ('5', '5'), ('1', '1')], max_length=30),
        ),
        migrations.AlterField(
            model_name='upload',
            name='price',
            field=models.PositiveIntegerField(max_length=100),
        ),
        migrations.AlterField(
            model_name='upload',
            name='toilets',
            field=models.CharField(blank=True, choices=[('4', '4'), ('6', '6'), ('3', '3'), ('2', '2'), ('7', '7'), ('9', '9'), ('0', '0'), ('8', '8'), ('5', '5'), ('1', '1')], max_length=30),
        ),
    ]
