# Generated by Django 3.1.4 on 2020-12-09 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homes', '0013_auto_20201205_1716'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upload',
            name='bathrooms',
            field=models.CharField(blank=True, choices=[('1', '1'), ('0', '0'), ('7', '7'), ('9', '9'), ('5', '5'), ('4', '4'), ('8', '8'), ('2', '2'), ('6', '6'), ('3', '3')], max_length=30),
        ),
        migrations.AlterField(
            model_name='upload',
            name='bedrooms',
            field=models.CharField(blank=True, choices=[('1', '1'), ('0', '0'), ('7', '7'), ('9', '9'), ('5', '5'), ('4', '4'), ('8', '8'), ('2', '2'), ('6', '6'), ('3', '3')], max_length=300),
        ),
        migrations.AlterField(
            model_name='upload',
            name='numberOfImages',
            field=models.CharField(choices=[('1', '1'), ('0', '0'), ('7', '7'), ('9', '9'), ('10', '10'), ('5', '5'), ('4', '4'), ('8', '8'), ('2', '2'), ('6', '6'), ('3', '3')], max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='upload',
            name='parking',
            field=models.CharField(blank=True, choices=[('1', '1'), ('0', '0'), ('7', '7'), ('9', '9'), ('5', '5'), ('4', '4'), ('8', '8'), ('2', '2'), ('6', '6'), ('3', '3')], max_length=30),
        ),
        migrations.AlterField(
            model_name='upload',
            name='toilets',
            field=models.CharField(blank=True, choices=[('1', '1'), ('0', '0'), ('7', '7'), ('9', '9'), ('5', '5'), ('4', '4'), ('8', '8'), ('2', '2'), ('6', '6'), ('3', '3')], max_length=30),
        ),
    ]
