# Generated by Django 3.1.4 on 2020-12-09 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homes', '0014_auto_20201209_1238'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upload',
            name='bathrooms',
            field=models.CharField(blank=True, choices=[('4', '4'), ('2', '2'), ('1', '1'), ('8', '8'), ('9', '9'), ('3', '3'), ('0', '0'), ('7', '7'), ('6', '6'), ('5', '5')], max_length=30),
        ),
        migrations.AlterField(
            model_name='upload',
            name='bedrooms',
            field=models.CharField(blank=True, choices=[('4', '4'), ('2', '2'), ('1', '1'), ('8', '8'), ('9', '9'), ('3', '3'), ('0', '0'), ('7', '7'), ('6', '6'), ('5', '5')], max_length=300),
        ),
        migrations.AlterField(
            model_name='upload',
            name='numberOfImages',
            field=models.CharField(choices=[('4', '4'), ('2', '2'), ('1', '1'), ('8', '8'), ('9', '9'), ('3', '3'), ('0', '0'), ('7', '7'), ('6', '6'), ('5', '5'), ('10', '10')], max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='upload',
            name='parking',
            field=models.CharField(blank=True, choices=[('4', '4'), ('2', '2'), ('1', '1'), ('8', '8'), ('9', '9'), ('3', '3'), ('0', '0'), ('7', '7'), ('6', '6'), ('5', '5')], max_length=30),
        ),
        migrations.AlterField(
            model_name='upload',
            name='toilets',
            field=models.CharField(blank=True, choices=[('4', '4'), ('2', '2'), ('1', '1'), ('8', '8'), ('9', '9'), ('3', '3'), ('0', '0'), ('7', '7'), ('6', '6'), ('5', '5')], max_length=30),
        ),
    ]
