# Generated by Django 3.1.4 on 2020-12-09 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homes', '0015_auto_20201209_1248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upload',
            name='bathrooms',
            field=models.CharField(blank=True, choices=[('3', '3'), ('5', '5'), ('4', '4'), ('1', '1'), ('7', '7'), ('9', '9'), ('8', '8'), ('0', '0'), ('2', '2'), ('6', '6')], max_length=30),
        ),
        migrations.AlterField(
            model_name='upload',
            name='bedrooms',
            field=models.CharField(blank=True, choices=[('3', '3'), ('5', '5'), ('4', '4'), ('1', '1'), ('7', '7'), ('9', '9'), ('8', '8'), ('0', '0'), ('2', '2'), ('6', '6')], max_length=300),
        ),
        migrations.AlterField(
            model_name='upload',
            name='numberOfImages',
            field=models.CharField(choices=[('3', '3'), ('5', '5'), ('4', '4'), ('1', '1'), ('7', '7'), ('9', '9'), ('8', '8'), ('0', '0'), ('2', '2'), ('10', '10'), ('6', '6')], max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='upload',
            name='parking',
            field=models.CharField(blank=True, choices=[('3', '3'), ('5', '5'), ('4', '4'), ('1', '1'), ('7', '7'), ('9', '9'), ('8', '8'), ('0', '0'), ('2', '2'), ('6', '6')], max_length=30),
        ),
        migrations.AlterField(
            model_name='upload',
            name='price',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='upload',
            name='toilets',
            field=models.CharField(blank=True, choices=[('3', '3'), ('5', '5'), ('4', '4'), ('1', '1'), ('7', '7'), ('9', '9'), ('8', '8'), ('0', '0'), ('2', '2'), ('6', '6')], max_length=30),
        ),
    ]
